name: android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ZIP_NAME: SalesMasterApp.zip
      UNZIP_DIR: project
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_PLATFORM: "platforms;android-34"
      ANDROID_BUILD_TOOLS: "build-tools;34.0.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify ZIP exists
        shell: bash
        run: |
          ls -la
          if [[ ! -f "$ZIP_NAME" ]]; then
            echo "ZIP '$ZIP_NAME' not found in repo root."
            exit 1
          fi

      - name: Unzip project
        shell: bash
        run: |
          rm -rf "$UNZIP_DIR"
          mkdir -p "$UNZIP_DIR"
          unzip -q "$ZIP_NAME" -d "$UNZIP_DIR"
          echo "Contents of $UNZIP_DIR:"
          ls -la "$UNZIP_DIR"

      - name: Detect Gradle project root
        id: gradleroot
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar nullglob
          ROOT=""
          for f in \
            "$UNZIP_DIR"/**/settings.gradle \
            "$UNZIP_DIR"/**/settings.gradle.kts \
            "$UNZIP_DIR"/**/build.gradle \
            "$UNZIP_DIR"/**/build.gradle.kts
          do
            if [[ -f "$f" ]]; then
              ROOT="$(dirname "$f")"
              break
            fi
          done
          if [[ -z "$ROOT" ]]; then
            echo "Could not find a Gradle project (no settings.gradle or build.gradle found)."
            exit 1
          fi
          echo "root=$ROOT" >> "$GITHUB_OUTPUT"
          echo "Gradle root is: $ROOT"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # ---------- FIXED STEP: sdkmanager was not on PATH in same step ----------
      - name: Install Android SDK (cmdline-tools)
        shell: bash
        run: |
          set -euo pipefail
          SDK="$ANDROID_SDK_ROOT"
          mkdir -p "$SDK"/cmdline-tools
          cd "$SDK"

          # Download and unpack latest commandline-tools
          curl -L -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdline-tools.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          rm -f cmdline-tools.zip

          # Make sdkmanager available **in this step**
          export ANDROID_SDK_ROOT="$SDK"
          export ANDROID_HOME="$SDK"
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH"

          echo "sdkmanager path = $(command -v sdkmanager || echo 'NOT FOUND')"
          if ! command -v sdkmanager >/dev/null 2>&1; then
            echo "sdkmanager not found after install."
            ls -la "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" || true
            exit 127
          fi

          # Accept licenses (ignore broken pipe noise)
          yes | sdkmanager --licenses || true

          # Required packages
          yes | sdkmanager "platform-tools" "${ANDROID_PLATFORM}" "${ANDROID_BUILD_TOOLS}"

          # Also export to later steps
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> "$GITHUB_ENV"
          echo "ANDROID_HOME=$ANDROID_HOME" >> "$GITHUB_ENV"
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
          echo "$ANDROID_SDK_ROOT/platform-tools" >> "$GITHUB_PATH"
          echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> "$GITHUB_PATH"
      # ------------------------------------------------------------------------

      - name: Set up Gradle (cache & tools)
        uses: gradle/actions/setup-gradle@v3

      - name: Fix Gradle wrapper permissions (if present)
        shell: bash
        run: |
          set -euo pipefail
          cd "${{ steps.gradleroot.outputs.root }}"
          if [[ -f "./gradlew" ]]; then
            chmod +x ./gradlew
          fi
          if [[ -f "gradle/wrapper/gradle-wrapper.jar" ]]; then
            chmod 644 gradle/wrapper/gradle-wrapper.jar
          fi

      - name: Build Debug APK
        working-directory: ${{ steps.gradleroot.outputs.root }}
        shell: bash
        run: |
          set -euo pipefail
          if [[ -x "./gradlew" ]]; then
            ./gradlew --version
            ./gradlew assembleDebug --stacktrace --no-daemon
          else
            echo "No gradlew found; using system Gradle"
            gradle --version
            gradle assembleDebug --stacktrace --no-daemon
          fi

      - name: Upload Debug APK(s)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: ${{ steps.gradleroot.outputs.root }}/**/*.apk
          if-no-files-found: warn
